dist: trusty
language: node_js
node_js:
  - 6.4
  - 7
  - 8

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
  - node_js: 9
    script:
      - yarn lint
      - yarn coverage
    after_success:
      - yarn codecov
  - os: osx
    node_js: 6.4
  - os: osx
    node_js: 8
