environment:
  matrix:
    - node_version: "8"
    - node_version: "6.4"

install:
  - ps: Install-Product node $env:node_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

cache:
 - node_modules -> yarn.lock
 - "%LOCALAPPDATA%/Yarn"

build: off
