version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  install:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-dep
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test_on_node6:
    <<: *defaults
    docker:
      - image: circleci/node:6-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  test_on_node7:
    <<: *defaults
    docker:
      - image: circleci/node:7-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  test_on_node8:
    <<: *defaults
    docker:
      - image: circleci/node:8-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn coverage
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test_on_node9:
    <<: *defaults
    docker:
      - image: circleci/node:9-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  lint:
    <<: *defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Linting
          command: yarn lint

  coverage:
    <<: *defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn codecov

workflows:
  version: 2
  testing:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
      - test_on_node6:
          requires:
            - install
      - test_on_node7:
          requires:
            - install
      - test_on_node8:
          requires:
            - install
      - test_on_node9:
          requires:
            - install
      - lint:
          requires:
            - install
      - coverage:
          requires:
            - test_on_node8
