version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  install:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-dep
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test_on_node6:
    <<: *defaults
    docker:
      - image: circleci/node:6-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  test_on_node7:
    <<: *defaults
    docker:
      - image: circleci/node:7-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  test_on_node8:
    <<: *defaults
    docker:
      - image: circleci/node:8-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn coverage
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test_on_node9:
    <<: *defaults
    docker:
      - image: circleci/node:9-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test

  test_e2e:
    <<: *defaults
    docker:
      - image: circleci/node:9-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: yarn test:e2e

  lint:
    <<: *defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Linting
          command: yarn lint

  coverage:
    <<: *defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn codecov

  docs:
    <<: *defaults
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:1d:85:85:6a:b5:a1:0c:ec:de:8c:94:a3:18:3d:00"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Prepare history
          command: |
            mkdir gh-pages
            cd gh-pages
            git init
            git remote add origin git@github.com:g-plane/rize.git
            git checkout -b gh-pages
            git pull origin gh-pages
            git config --global user.name "Pig Fang"
            git config --global user.email "g-plane@hotmail.com"
            cd ..
      - run:
          name: Generate docs
          command: yarn build:docs
      - run:
          name: Add docs to VCS
          command: cp -r docs/dist/** gh-pages
      - run:
          name: Publish
          command: |
            cd gh-pages
            git add .
            git commit --allow-empty -m "Build docs at $CIRCLE_SHA1 [skip ci]"
            git push origin gh-pages

workflows:
  version: 2
  testing:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
      - test_on_node6:
          requires:
            - install
      - test_on_node7:
          requires:
            - install
      - test_on_node8:
          requires:
            - install
      - test_on_node9:
          requires:
            - install
      - test_e2e:
          requires:
            - install
      - lint:
          requires:
            - install
      - coverage:
          requires:
            - test_on_node8
      - docs:
          requires:
            - install
